<?php
/**
 * Catálogo de exemplo. Troque pelos seus produtos aqui (e rode o script de novo)
 * ou importe um CSV em Produtos > Importar.
 *
 * Peso em kg e medidas em cm (comprimento, largura, altura) da CAIXA de envio:
 * é isso que o Melhor Envio usa para cotar o frete.
 */

defined( 'ABSPATH' ) || exit;

function fv_conteudo_categorias() {
	return array(
		'bannetons-e-cestos'   => array(
			'nome'      => 'Bannetons e cestos',
			'menu'      => 'Bannetons',
			'descricao' => 'Cestos de fermentação em vime e ratã para dar forma e as marcas em espiral ao pão.',
			'cor'       => array( 0xFB, 0xF1, 0xDE ),
		),
		'panelas-e-assadeiras' => array(
			'nome'      => 'Panelas e assadeiras',
			'menu'      => 'Panelas',
			'descricao' => 'Ferro fundido que segura o vapor e dá casca crocante no forno de casa.',
			'cor'       => array( 0xE6, 0xEC, 0xFB ),
		),
		'utensilios'           => array(
			'nome'      => 'Utensílios de bancada',
			'menu'      => 'Utensílios',
			'descricao' => 'Lâminas, raspadores, balanças e termômetros para trabalhar a massa com precisão.',
			'cor'       => array( 0xEC, 0xEE, 0xE8 ),
		),
		'farinhas-e-fermentos' => array(
			'nome'      => 'Farinhas e fermentos',
			'menu'      => 'Farinhas',
			'descricao' => 'Farinhas brasileiras selecionadas e fermento natural desidratado para começar hoje.',
			'cor'       => array( 0xF4, 0xEC, 0xE0 ),
		),
	);
}

function fv_conteudo_produtos() {
	return array(
		array(
			'sku'       => 'FV-BAN-RED',
			'nome'      => 'Banneton de vime redondo',
			'categoria' => 'bannetons-e-cestos',
			'forma'     => 'banneton',
			'destaque'  => true,
			'resumo'    => 'Cesto de fermentação em vime natural com capa de linho. Deixa a espiral clássica na casca.',
			'descricao' => "Feito de vime natural, o banneton absorve a umidade da superfície da massa durante a fermentação final e ajuda o pão a manter a forma até o forno.\n\n<strong>Como usar:</strong> polvilhe farinha de arroz, coloque a massa com a emenda para cima e leve à geladeira de 8 a 14 horas.\n\n<strong>Cuidados:</strong> não lave com sabão. Retire o excesso de farinha com uma escova seca e deixe secar ao ar.",
			'ficha'     => array( 'Material' => 'Vime natural', 'Acompanha' => 'Capa de linho' ),
			'peso'      => '0.35',
			'medidas'   => array( 25, 25, 12 ),
			'variacoes' => array(
				array( 'tamanho' => '18 cm (massa até 500 g)', 'sufixo' => '18', 'preco' => '79.90', 'estoque' => 12, 'peso' => '0.30', 'medidas' => array( 21, 21, 11 ) ),
				array( 'tamanho' => '22 cm (massa até 1 kg)', 'sufixo' => '22', 'preco' => '89.90', 'estoque' => 8, 'peso' => '0.40', 'medidas' => array( 25, 25, 12 ) ),
			),
		),
		array(
			'sku'       => 'FV-BAN-OVL',
			'nome'      => 'Banneton oval de vime 25 cm',
			'categoria' => 'bannetons-e-cestos',
			'forma'     => 'banneton',
			'resumo'    => 'Formato bâtard para pães alongados de até 900 g de massa. Com capa de linho.',
			'descricao' => "O formato oval é o preferido para pães de sanduíche: as fatias saem mais uniformes.\n\nComporta massas de 700 g a 900 g. Acompanha capa de linho para massas mais hidratadas.",
			'ficha'     => array( 'Material' => 'Vime natural', 'Medidas internas' => '25 × 15 × 8 cm' ),
			'preco'     => '94.90',
			'estoque'   => 0,
			'peso'      => '0.40',
			'medidas'   => array( 28, 18, 11 ),
		),
		array(
			'sku'       => 'FV-PAN-FF24',
			'nome'      => 'Panela de ferro fundido esmaltada 24 cm',
			'categoria' => 'panelas-e-assadeiras',
			'forma'     => 'panela',
			'destaque'  => true,
			'pesado'    => true,
			'resumo'    => 'Panela de 4,2 litros com tampa pesada que prende o vapor. Vai ao forno a 260 °C.',
			'descricao' => "A tampa pesada prende o vapor que sai da massa nos primeiros 20 minutos, e é isso que faz o pão crescer e formar a pestana.\n\n<strong>Como usar:</strong> preaqueça a panela vazia com a tampa por 45 minutos a 250 °C. Coloque o pão, tampe por 20 minutos, destampe e asse mais 20 a 25 minutos.\n\nEsmalte interno claro, que facilita ver a cor da base do pão. Serve também para carnes, feijão e risoto.",
			'ficha'     => array( 'Capacidade' => '4,2 litros', 'Diâmetro interno' => '24 cm', 'Temperatura máxima' => '260 °C', 'Fogão' => 'Gás, elétrico e indução' ),
			'preco'     => '459.90',
			'promocao'  => '399.90',
			'estoque'   => 6,
			'peso'      => '5.20',
			'medidas'   => array( 34, 30, 18 ),
		),
		array(
			'sku'       => 'FV-PAN-COMBO',
			'nome'      => 'Combo cooker de ferro fundido',
			'categoria' => 'panelas-e-assadeiras',
			'forma'     => 'panela',
			'pesado'    => true,
			'resumo'    => 'Frigideira funda e panela que se encaixam: o pão entra pela parte rasa, sem queimar as mãos.',
			'descricao' => "O combo cooker é a panela de ferro virada ao contrário: você coloca a massa na parte rasa e cobre com a funda. Fica muito mais fácil transferir e cortar o pão.\n\nVem pré-curado com óleo vegetal. As duas peças também funcionam separadas no fogão.",
			'ficha'     => array( 'Capacidade' => '3 litros', 'Diâmetro' => '26 cm', 'Acabamento' => 'Ferro pré-curado' ),
			'preco'     => '329.90',
			'estoque'   => 4,
			'peso'      => '6.00',
			'medidas'   => array( 40, 30, 16 ),
		),
		array(
			'sku'       => 'FV-UTE-LAME',
			'nome'      => 'Lâmina para pestana com 5 refis',
			'categoria' => 'utensilios',
			'forma'     => 'lamina',
			'destaque'  => true,
			'resumo'    => 'Cabo de madeira e 5 lâminas de aço. O corte certo para a orelha do pão abrir no forno.',
			'descricao' => "A lâmina (lame) faz o corte que direciona a abertura do pão no forno, a pestana.\n\nSegure a 30° em relação à massa e faça um corte único e firme, de 1 cm de profundidade. Troque a lâmina quando começar a arrastar a massa.",
			'ficha'     => array( 'Cabo' => 'Madeira de reflorestamento', 'Acompanha' => '5 lâminas de aço inox e protetor' ),
			'preco'     => '39.90',
			'estoque'   => 40,
			'peso'      => '0.08',
			'medidas'   => array( 18, 6, 3 ),
		),
		array(
			'sku'       => 'FV-UTE-RASP',
			'nome'      => 'Raspador de massa em aço inox',
			'categoria' => 'utensilios',
			'forma'     => 'raspador',
			'resumo'    => 'Divide, levanta e modela a massa sem grudar. Régua em centímetros na lâmina.',
			'descricao' => "O raspador (bench scraper) é a extensão da sua mão na bancada: divide a massa, ajuda na pré-modelagem e limpa a bancada no final.\n\nLâmina de aço inox com régua gravada de 0 a 15 cm e cabo de polipropileno.",
			'ficha'     => array( 'Material' => 'Aço inox 430', 'Lâmina' => '15 × 11 cm' ),
			'preco'     => '34.90',
			'estoque'   => 25,
			'peso'      => '0.20',
			'medidas'   => array( 18, 13, 3 ),
		),
		array(
			'sku'       => 'FV-UTE-ESPAT',
			'nome'      => 'Kit 2 espátulas flexíveis para tigela',
			'categoria' => 'utensilios',
			'forma'     => 'raspador',
			'resumo'    => 'Espátulas de polipropileno que acompanham a curva da tigela e não deixam massa para trás.',
			'descricao' => 'Duas espátulas flexíveis, uma média e uma grande, para tirar a massa da tigela sem rasgar a rede de glúten. Podem ir à lava-louças.',
			'ficha'     => array( 'Material' => 'Polipropileno sem BPA', 'Quantidade' => '2 unidades' ),
			'preco'     => '19.90',
			'estoque'   => 30,
			'peso'      => '0.06',
			'medidas'   => array( 16, 12, 2 ),
		),
		array(
			'sku'       => 'FV-UTE-TERMO',
			'nome'      => 'Termômetro digital espeto',
			'categoria' => 'utensilios',
			'forma'     => 'termometro',
			'resumo'    => 'Mede a massa, a água e o miolo: o pão está pronto quando passa de 96 °C.',
			'descricao' => "A temperatura da massa é o que mais muda o tempo de fermentação. Mire em 24 °C a 26 °C depois de misturar, ajustando a temperatura da água.\n\nFaixa de -50 °C a 300 °C, leitura em 3 segundos e desligamento automático. Acompanha bateria.",
			'ficha'     => array( 'Faixa' => '-50 °C a 300 °C', 'Precisão' => '±1 °C', 'Bateria' => 'LR44 (inclusa)' ),
			'preco'     => '69.90',
			'estoque'   => 15,
			'peso'      => '0.10',
			'medidas'   => array( 25, 6, 3 ),
		),
		array(
			'sku'       => 'FV-UTE-BAL',
			'nome'      => 'Balança digital de precisão 5 kg',
			'categoria' => 'utensilios',
			'forma'     => 'balanca',
			'destaque'  => true,
			'resumo'    => 'Pesa de 1 g a 5 kg com função tara. Receita de pão se mede em gramas, não em xícaras.',
			'descricao' => "Uma xícara de farinha pode pesar de 110 g a 160 g, dependendo de como você enche. Por isso toda receita de fermentação natural é em gramas.\n\nPlataforma de vidro temperado, função tara para pesar direto na tigela e troca entre g, kg e ml.",
			'ficha'     => array( 'Capacidade' => '1 g a 5 kg', 'Funções' => 'Tara, g/kg/ml', 'Pilhas' => '2 × AAA (inclusas)' ),
			'preco'     => '119.90',
			'estoque'   => 10,
			'peso'      => '0.60',
			'medidas'   => array( 24, 20, 5 ),
		),
		array(
			'sku'       => 'FV-FAR-T1-5',
			'nome'      => 'Farinha de trigo tipo 1 orgânica 5 kg',
			'categoria' => 'farinhas-e-fermentos',
			'forma'     => 'saco',
			'pesado'    => true,
			'resumo'    => 'Farinha orgânica com 12% de proteína, de moinho do Paraná. Boa para hidratações de 68% a 75%.',
			'descricao' => "Farinha de trigo tipo 1, orgânica certificada, com 12% de proteína: força suficiente para pães de fermentação longa.\n\nComece com 70% de hidratação (700 g de água para 1 kg de farinha) e suba aos poucos.",
			'ficha'     => array( 'Proteína' => '12 g por 100 g', 'Origem' => 'Paraná', 'Validade' => '6 meses' ),
			'preco'     => '64.90',
			'estoque'   => 3,
			'peso'      => '5.10',
			'medidas'   => array( 35, 25, 10 ),
		),
		array(
			'sku'       => 'FV-FAR-CENT-1',
			'nome'      => 'Farinha integral de centeio 1 kg',
			'categoria' => 'farinhas-e-fermentos',
			'forma'     => 'saco',
			'resumo'    => 'Acelera o fermento e dá sabor mais ácido e terroso. Use de 10% a 20% na receita.',
			'descricao' => "O centeio integral tem mais nutrientes para as leveduras, por isso é o melhor alimento para um fermento natural preguiçoso.\n\nNa massa, comece trocando 10% da farinha branca por centeio.",
			'ficha'     => array( 'Tipo' => 'Integral, moagem em pedra', 'Validade' => '4 meses' ),
			'preco'     => '29.90',
			'promocao'  => '24.90',
			'estoque'   => 20,
			'peso'      => '1.05',
			'medidas'   => array( 20, 14, 7 ),
		),
		array(
			'sku'       => 'FV-FERM-DES',
			'nome'      => 'Fermento natural desidratado 20 g',
			'categoria' => 'farinhas-e-fermentos',
			'forma'     => 'pote',
			'destaque'  => true,
			'resumo'    => 'Levain ativo de 8 anos, desidratado. Reativa em 3 a 5 dias em vez de 7 a 14.',
			'descricao' => "Um fermento natural maduro, seco a baixa temperatura para preservar leveduras e bactérias.\n\n<strong>Reativação:</strong> misture 5 g com 20 g de água e 20 g de farinha. Alimente a cada 24 horas na proporção 1:5:5 até dobrar de volume em 6 horas.",
			'ficha'     => array( 'Conteúdo' => '20 g (4 reativações)', 'Validade' => '12 meses em local seco' ),
			'preco'     => '34.90',
			'estoque'   => 50,
			'peso'      => '0.05',
			'medidas'   => array( 12, 9, 2 ),
		),
		array(
			'sku'       => 'FV-KIT-INI',
			'nome'      => 'Kit primeiro pão',
			'categoria' => 'bannetons-e-cestos',
			'forma'     => 'banneton',
			'resumo'    => 'Banneton redondo 22 cm, lâmina com 5 refis, raspador inox e fermento desidratado.',
			'descricao' => 'Tudo o que falta para o primeiro pão, além da panela: banneton redondo de 22 cm com capa, lâmina com 5 refis, raspador de massa em inox e 20 g de fermento natural desidratado. Sai mais barato do que comprar separado.',
			'ficha'     => array( 'Itens' => '4 produtos', 'Economia' => 'R$ 59,70 em relação aos itens avulsos (R$ 199,60)' ),
			'preco'     => '164.90',
			'promocao'  => '139.90',
			'estoque'   => 7,
			'peso'      => '0.75',
			'medidas'   => array( 26, 26, 14 ),
		),
	);
}
